apiVersion: v1
kind: Namespace
metadata:
  name: istio-starter-ns
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: istio-starter-ns
  name: istio-starter-fe-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: istio-starter-ns
  name: istio-starter-be-sa